version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 20
    ignore:
      # Keep this pinned to the version of Node that we're running
      - dependency-name: "@types/node"
        versions: [">=23"]
      # This has tight coupling to the version of SWC, which is provided by
      # Meteor. Assume we'll upgrade this when we take Meteor upgrades.
      - dependency-name: "@swc/plugin-styled-components"
    groups:
      aws:
        patterns:
          - "@aws-sdk/*"
      bugsnag:
        patterns:
          - "@bugsnag/*"
      google:
        patterns:
          - "@googleapis/*"
          - gaxios
      fontawesome:
        patterns:
          - "@fortawesome/*"
      i18next:
        patterns:
          - "i18next"
          - "react-i18next"
      react:
        patterns:
          - "react"
          - "react-dom"
      slate:
        patterns:
          - "slate"
          - "slate-history"
          - "slate-react"
      testing-library:
        patterns:
          - "@testing-library/*"
      stylelint:
        patterns:
          - "stylelint"
          - "stylelint-*"
      oxlint:
        patterns:
          - "oxlint"
          - "oxlint-tsgolint"
      typescript-eslint:
        patterns:
          - "typescript-eslint"
          - "@typescript-eslint/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
