version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 20
    ignore:
      # All of these dependencies require Node v16 or greater
      - dependency-name: "discord.js"
        versions: [">=13"]
    groups:
      aws:
        patterns:
          - "@aws-sdk/*"
      google:
        patterns:
          - "@googleapis/*"
          - gaxios
      fontawesome:
        patterns:
          - "@fortawesome/*"
      react:
        patterns:
          - "react"
          - "react-dom"
      slate:
        patterns:
          - "slate"
          - "slate-history"
          - "slate-react"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
